### ISSUE TITLE
TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by asdf404** [asdf404/torrent-trackers-monitoring-bot#1]
```
TypeError: Parameter "url" must be a string, not undefined
     at Url.parse (url.js:102:11)
     at Object.urlParse [as parse] (url.js:96:5)
     at Request.request [as _callback] (/service/src/fetchers/rutracker.js:16:26)
     at Request.self.callback (/service/node_modules/request/request.js:188:22)
     at emitTwo (events.js:125:13)
     at Request.emit (events.js:213:7)
     at Request.<anonymous> (/service/node_modules/request/request.js:1171:10)
     at emitOne (events.js:115:13)
     at Request.emit (events.js:210:7)
     at IncomingMessage.<anonymous> (/service/node_modules/request/request.js:1091:12)
     at Object.onceWrapper (events.js:314:30)
     at emitNone (events.js:110:20)
     at IncomingMessage.emit (events.js:207:7)
     at endReadableNT (_stream_readable.js:1045:12)
     at _combinedTickCallback (internal/process/next_tick.js:138:11)
     at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by asdf404** [comment]
Fixed in 728a8a647350a8f72a776828331f603085f9cb2e
